name: Obsidian Style Checker
on:
  push:
    branches:
      - develop

jobs:
  style-check:
    name: Obsidian Style Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.17.1'

      - name: Install dependencies
        run: npm ci
        working-directory: "./Dev Tools/obsidian-style-checker"

      - name: Run Obsidian Style Checker
        run: npx obsidian-style-checker
        working-directory: "./Dev Tools/obsidian-style-checker"
        env:
          ASANA_ACCESS_TOKEN: "${{ secrets.ASANA_ACCESS_TOKEN }}"
          ASANA_WORKSPACE: "${{ vars.ASANA_WORKSPACE }}"
          ASANA_PROJECT: "${{ vars.ASANA_STYLE_CHECKER_PROJECT }}"
          ASANA_SECTION: "${{ vars.ASANA_STYLE_CHECKER_SECTION }}"
